### ISSUE TITLE
Cancel/abort file upload

### ISSUE THREAD

**Issue by vhcraig** [laravel/vapor-js#5]
As it stands it is not possible to cancel or abort file uploads using this package.

The app I'm making allows uploads of multiple files at about 1gb each and will need to be uploaded to S3 directly, which works really well but it's become apparent that I need to be able to cancel uploads which does not seem to be possible.

Are there any plans to implement cancel or abort functionality?

**Comment by robmpreston** [comment]
Added here

https://github.com/laravel/vapor-js/pull/14

**Comment by bkintanar** [comment]
#14 has been merged, looks like this issue can be closed now.
